[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/models",
    "crates/service",
]

[profile.release]
lto = true
strip = true
codegen-units = 1

[workspace.dependencies]
tokio = { version = "1.28", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
